import type { MetaData } from "./types";

export const flashCardCodes = [
  "pachelbel_bar1.1_lh_d4",
  "pachelbel_bar1.2_rh_fs4",
  "pachelbel_bar1.3_rh_a4",
  "pachelbel_bar1.4_rh_d5",
  "pachelbel_bar1.5_lh_a3",
  "pachelbel_bar1.6_rh_cs4",
  "pachelbel_bar1.7_rh_e4",
  "pachelbel_bar1.8_rh_a4",
  "pachelbel_bar2.1_lh_b3",
  "pachelbel_bar2.2_rh_d4",
  "pachelbel_bar2.3_rh_fs4",
  "pachelbel_bar2.4_rh_b4",
  "pachelbel_bar2.5_lh_fs3",
  "pachelbel_bar2.6_rh_a3",
  "pachelbel_bar2.7_rh_cs4",
  "pachelbel_bar2.8_rh_fs4",
  "pachelbel_bar3.1_lh_g3",
  "pachelbel_bar3.2_rh_b3",
  "pachelbel_bar3.3_rh_d4",
  "pachelbel_bar3.4_rh_g4",
  "pachelbel_bar3.5_lh_a3",
  "pachelbel_bar3.6_lh_cs4",
  "pachelbel_bar3.7_lh_e4",
  "pachelbel_bar3.8_lh_g4",
  "pachelbel_bar9.1_rh_a4-d5-fs5",
  "pachelbel_bar9.2_lh_d3",
  "pachelbel_bar9.3_lh_fs3",
  "pachelbel_bar9.4_lh_a3",
  "pachelbel_bar9.5_rh_a4-cs5-e5",
  "pachelbel_bar9.6_lh_a2",
  "pachelbel_bar9.7_lh_cs3",
  "pachelbel_bar9.8_lh_e3",
];

export const pieceNames: Record<string, MetaData> = {
  pachelbel: { title: "J. Pachelbel", artist: "Canon D dur" },
};
