export const flashCardCodes = [
  "pachelbel_bar1_lh_a3",
  "pachelbel_bar1_lh_d4",
  "pachelbel_bar1_rh_a4",
  "pachelbel_bar1_rh_a4",
  "pachelbel_bar1_rh_cs4",
  "pachelbel_bar1_rh_d5",
  "pachelbel_bar1_rh_e4",
  "pachelbel_bar1_rh_fs4",
  "pachelbel_bar3_lh_a3",
  "pachelbel_bar3_lh_cs4",
  "pachelbel_bar3_lh_e4",
  "pachelbel_bar3_lh_g3",
  "pachelbel_bar3_lh_g4",
  "pachelbel_bar3_rh_b3",
  "pachelbel_bar3_rh_d4",
  "pachelbel_bar3_rh_g4",
  "pachelbel_bar9_lh_a2",
  "pachelbel_bar9_lh_a3",
  "pachelbel_bar9_lh_cs3",
  "pachelbel_bar9_lh_d3",
  "pachelbel_bar9_lh_e3",
  "pachelbel_bar9_lh_fs3",
  "pachelbel_bar9_rh_a4-cs5-e5",
  "pachelbel_bar9_rh_a4-d5-fs5",
];

export const pieceNames: Record<string, string> = {
  pachelbel: "Canon D dur – J. Pachelbel",
};
